openapi: 3.0.3
info:
  title: CMS Registration
  version: 1.0.0
  description: Contract for user registration.
paths:
  /register:
    get:
      summary: Show registration form
      responses:
        "200":
          description: Registration form page
    post:
      summary: Submit registration form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                  description: User email address (RFC 5322)
                password:
                  type: string
                  description: User password
      responses:
        "302":
          description: Redirect to login on success
          headers:
            Location:
              schema:
                type: string
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  fieldErrors:
                    type: object
                    additionalProperties:
                      type: string
              examples:
                missingFields:
                  summary: Missing required fields
                  value:
                    error: "Validation error"
                    fieldErrors:
                      email: "Email is required"
                      password: "Password is required"
        "409":
          description: Email already in use
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Registration failed due to system error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
